// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSiVHyYHQPlE_asrEwls-vvJYFTbxJxig',
    appId: '1:903206061970:web:8c840012af84dfd4c2a34b',
    messagingSenderId: '903206061970',
    projectId: 'animateon1',
    authDomain: 'animateon1.firebaseapp.com',
    storageBucket: 'animateon1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2lbRLBoaTbYAbEMZYKQIcfT1EoWfr8o',
    appId: '1:903206061970:android:d6e6a2a9e6de2245c2a34b',
    messagingSenderId: '903206061970',
    projectId: 'animateon1',
    storageBucket: 'animateon1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoeiXLvOrIbhq1gVa1HJPCOZrKT0T9knE',
    appId: '1:903206061970:ios:aa8355b907983a53c2a34b',
    messagingSenderId: '903206061970',
    projectId: 'animateon1',
    storageBucket: 'animateon1.appspot.com',
    iosClientId: '903206061970-l9bforvci31h58uonrdffqhr0aof87bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.animateon1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoeiXLvOrIbhq1gVa1HJPCOZrKT0T9knE',
    appId: '1:903206061970:ios:a661210c32fe45e1c2a34b',
    messagingSenderId: '903206061970',
    projectId: 'animateon1',
    storageBucket: 'animateon1.appspot.com',
    iosClientId: '903206061970-sf871vbv5eju6oph7dsuga34s61jvkui.apps.googleusercontent.com',
    iosBundleId: 'com.example.animateon1.RunnerTests',
  );
}
